name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.19', '1.20', '1.21']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Verify Go installation
      run: |
        go version
        go env GOROOT
        go env GOPATH
        go env GOMODCACHE
        
    - name: Download dependencies
      run: go mod download
      
    - name: Verify dependencies
      run: go mod verify
      
    - name: Run tests
      run: go test -v -race ./...
      
    - name: Run benchmarks
      run: go test -bench=. -benchmem
  
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Verify Go installation
      run: go version
        
    - name: Download dependencies
      run: go mod download
        
    - name: Run coverage tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      
    - name: Refresh Go Report Card
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        curl -d "repo=github.com/yongPhone/gyaml" https://goreportcard.com/checks || true 