name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.19', '1.20', '1.21']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
        
    - name: Download dependencies
      run: go mod download
      
    - name: Run tests
      run: go test -v -race ./...
      
    - name: Run benchmarks
      run: go test -bench=. -benchmem
  
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
        
    - name: Download dependencies
      run: go mod download
        
    - name: Run coverage tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4 